### ISSUE TITLE
integrating with SASS or LESS

### ISSUE THREAD

**Issue by weedkiller** [benembery/dotnet-bundle-transformer-theme-builder#1]
this is just great 👍 , looks like bindtuning... trying to extend it to orchard... can I integrate it with LESS or SASS.
Can you update the sample please

**Comment by benembery** [comment]
Hey @weedkiller, 

I'm afraid I'm not familiar with bindtuning or Orchard. 

I'd previously investigated implementing this for SASS for a question on StackOverflow. However, I don't believe this would ever work. The SASS implementation doesn't allow adding variables like we can with LESS. That said this implementation is 3 years old and no doubt well out-of-date. I would welcome pull requests to support SASS.

**Comment by weedkiller** [comment]
thanks for the response @benembery , check out [this site](http://bit.ly/1KEw4zA) it uses ASHX or webcontroller/webAPI to save the changes to the theme, this was what I was referring to.

OrchardProject.net  is open source

by the way great work, gold medal! 🥇
